### ISSUE TITLE
Give different colors to markers wanting to share and wanting to connect

### ISSUE THREAD

**Issue by zorun** [JocelynDelalande/wifi-with-me#12]
Currently, all markers on the map have the same color (blue).

It would be nice to have a different color, to distinguish people that want to share their connection and people that want to connect to the network.

**Comment by JocelynDelalande** [comment]
Patch proposed in https://github.com/JocelynDelalande/wifi-with-me/tree/multicolor-map-icons

@opi as a js & leaflet padawan, I would appreciate your input :)

**Comment by zorun** [comment]
It seems that the position of the markers is slightly wrong, for some reason (the position is different from that of the master branch, and does not align well with the field-of-vision circles).

Maybe a rounding error?

**Comment by JocelynDelalande** [comment]
Oh you're right...

> It seems that the position of the markers is slightly wrong, for some reason (the position is different from that of the master branch, and does not align well with the field-of-vision circles).

No, I think it's the offsets here : https://github.com/JocelynDelalande/wifi-with-me/blob/multicolor-map-icons/assets/map.js#L16 

To be honest, I copy-pasted the example, now I have to figure out how these options work actually ;)

**Comment by opi** [comment]
See http://leafletjs.com/reference.html#icon

iconAnchor is the position of the "tip" of the icon. If you think of a regular marker, iconAnchor is "bottom center".

**Comment by opi** [comment]
In our case, with marker-icon.png (https://github.com/JocelynDelalande/wifi-with-me/blob/master/assets/leaflet/images/marker-icon.png), iconSize and iconAnchor seems to be alright.

**Comment by zorun** [comment]
Thanks, it's now merged into master!
