### ISSUE TITLE
Points on the map don't appear immediately after adding a point

### ISSUE THREAD

**Issue by zorun** [JocelynDelalande/wifi-with-me#13]
When adding a point, we are redirected to the `/thanks` page, which has a link to the `/map` page.  However, when following the link, the point that was just added does not appear. Reloading the page is enough to see the new point appear.

My guess is that the JSON file is generated *after* the request is served, and not before, so that the old version of the JSON is used for the first request.

**Comment by JocelynDelalande** [comment]
Reproduced, not figured out yet, on /map right after adding a point the public.json downloaded is ok (containing the last point added)...

**Comment by opi** [comment]
GeoJSON file is rebuild during the 'POST' route, right before redirecting to the `/thanks` page, see https://github.com/JocelynDelalande/wifi-with-me/blob/master/backend.py#L204

Maybe we could juste add a random query string to the GeoJSON file, to bypass browser cache.

**Comment by JocelynDelalande** [comment]
> Maybe we could juste add a random query string to the GeoJSON file, to
> bypass browser cache.

It's worth a try :)

**Comment by JocelynDelalande** [comment]
@opi You inspired me :) 

I tried (as exercice for me, I have to admit) to do it a better way using file actual json modification time instead of curent clock as querystring. What do you think ?

@zorun can you confirm it now works for you ?
