### ISSUE TITLE
Making a config file

### ISSUE THREAD

**Issue by julienth37** [JocelynDelalande/wifi-with-me#16]
Here is the diff files of the edit made by TDN for adaptation.
The replacement of the default image was done by replacing the photos files.

The most of that edit was for the isp info, the use of the isp.json file made for db.ffdn.org  seems to be interesting because all info there are already in and formated properly. Using it as sources 90% of the work was already does. The 10 % remaining are text editing and the logo/picture changes.

We also use the init.d script done for ansible (without ansible) by copying and editing the wwm_install_dir and wwm_user)

assets/form.js
-------------------------------------------------------------------------------------------------------------------
```javascript
5,7c5,7
<         lat: ($('#latitude').val()) ? $('#latitude').val() : 47.218371,
<         lng: ($('#longitude').val()) ? $('#longitude').val() : -1.553621,
<         zoom: 13,
---
>         lat: ($('#latitude').val()) ? $('#latitude').val() : 47.395717,
>         lng: ($('#longitude').val()) ? $('#longitude').val() : 0.682634,
>         zoom: 12,
```
asset/map.js
-------------------------------------------------------------------------------------------------------------------
```javascript
5,7c5,7
<         lat: 47.218371,
<         lng: -1.553621,
<         zoom: 13,
---
>         lat: 47.395717,
>         lng: 0.682634,
>         zoom: 12,
```
views/base.tpl
-------------------------------------------------------------------------------------------------------------------
```php
5c5
<     <title>FAIMaison �^�^� contribution à l'expérimentation wifi</title>
---
>     <title>TDN �^�^� contribution à l'expérimentation wifi</title>
43,44c43,44
<         Vos données personnelles sont stockées sur les serveurs de FAImaison
<       durant <em>un an</em>, sauf demande de votre part. <br />
---
>         Vos données personnelles sont stockées sur les serveurs de TDN
>       durant <em>un an</em>, sauf demande de votre part. <br/>
47c47
<       collectivités. Des membres individuels de FAImaison seront toutefois amenés
---
>       collectivités. Des membres individuels de TDN seront toutefois amenés
49c49
<       pas confiance en FAImaison.
---
>       pas confiance en TDN.
51c51
<         <a href="https://www.faimaison.net" target="_blank">FAImaison.net</a> -
---
>         <a href="https://www.tdn-fai.net" target="_blank">tdn-fai.net</a> -
```
views/thanks.tpl
-------------------------------------------------------------------------------------------------------------------
```php
12c12
< <a href="https://www.faimaison.net/pages/contact.html">la page contact</a> de
---
> <a href="http://www.tdn-fai.net/contact-rejoindre">la page contact</a> de
```
views/wifi-form.tpl
-------------------------------------------------------------------------------------------------------------------
```php
22,23c22,23
< L'association <a href="http://faimaison.net">FAIMaison</a> expérimente à
< grande échelle (Nantes et environs) la création d'un réseau sans-fil à
---
> L'association <a href="http://tdn-fai.net">Touraine Data Network</a> expérimente à
> grande échelle (Tours et ses environs) la création d'un réseau sans-fil à
151c151
<                  id="search" placeholder="rue du calvaire, nantes" class="form-control" />
---
>                  id="search" placeholder="rue Littré, Tours" class="form-control" />
209c209
< seulement au bureau de FAIMaison.<br />
---
> seulement au bureau de TDN.<br/>
```

**Comment by JocelynDelalande** [comment]
> Here is the diff files of the edit made by TDN for adaptation.
> The replacement of the default image was done by replacing the photos files.

Thanks :)

> The most of that edit was for the isp info, the use of the isp.json file made for db.ffdn.org seems to be interesting because all info there are already in and formated properly. Using it as sources 90% of the work was already does. The 10 % remaining are text editing and the logo/picture changes.

That (using db.ffdn.org information) seems over-engineered to me. BTW, the use of wwm is not limited to FFDN ISPs.

I think two minor edits will make the whole thing re-usable by anyone :

- source the default coordinates not from `map.js` var but from an attribute on the map dom element (`<div id="map" start_lon="…" start_lat="...">`).
- offer the ability to specify a dir to get customized templates from.

> We also use the init.d script done for ansible (without ansible) by copying and editing the wwm_install_dir and wwm_user)

This part can for sure be simplified/made more generic (but that's another issue).

**Comment by opi** [comment]
+1 for NOT using db.ffdn.org data, as WifiWithMe is not meant to be used only by FFDN ISPs.

Why not using a custom templates folder, but I think we still need a config file, maybe a simple json file parsed by our rendering function to expose variables in every template.

For example, the `<div id="map" start_lon="…" start_lat="...">`  could be a simple solution, but every instance need to overwrite the map template to specifiy default coordinates.

**Comment by opi** [comment]
s / simple json file / simple json or py file /  ;)

**Comment by JocelynDelalande** [comment]
@zorun is that ability to use custom templates enough to make you able to use master instead of a forked branch ?

**Comment by opi** [comment]
Hope that we could use a regular config file, to set default title, gps coordinates, template dirs, ...
According to me templates files are not the place to configure an application.

**Comment by JocelynDelalande** [comment]
@opi yeah, and that's why the ticket is still open.. But for now, at least, that allows to "do everything" for now :-)

**Comment by bikepunk** [comment]
https://code.ffdn.org/FFDN/wifi-with-me/issues/19
