### ISSUE TITLE
Permalink to map points

### ISSUE THREAD

**Issue by JocelynDelalande** [JocelynDelalande/wifi-with-me#18]
Going to the permalink url should open the map, zooming on the point and open its popup.

**Comment by opi** [comment]
nice feature request indeed ! I got to find some time to hack on this.

**Comment by opi** [comment]
we should find a way to display the permalink on the /thanks page.

Does save_to_db() can return the id ?

**Comment by JocelynDelalande** [comment]
<3

Yep, I was thinking… what about redirecting directly to the permaling (that means: the map view) (with some notification-like extra message about the fact we just inserted) ?



> we should find a way to display the permalink on the /thanks page.

> Does save_to_db() can return the id ?

Sure thing. `return db.lastrowid`

**Comment by opi** [comment]
Using an url hash ( like `#123` ) is convenient for a javascript use, but not for python.

I manage to redirect user to `/map#123`, but I can't use this id in python code to display a notification. So what about redirecting to `/thanks?id=123` (or even `/map?id=123`) and display the permalink url in a nice way.

Not sure what is the *kiss* to go, feel a little confused and tired right now. I'm just going to commit the "get the last inserted id" related code.

**Comment by JocelynDelalande** [comment]
I tested permalinks as you implemented them, works well :-)

> I manage to redirect user to /map#123, but I can't use this id in python code to display a notification. So what about redirecting to /thanks?id=123 (or even /map?id=123) and display the permalink url in a nice way.

You mean, in the « thanks » notification text ? good idea.

> Using an url hash ( like #123 ) is convenient for a javascript use, but not for python.

Oh you're right, implementing your previous suggestion requires not to use a hash but something in the actual URL.

So, if we redirect to map directly, I see two solutions :

1) Support two formats of permalinks exist (current anchor-permalink and real-url-permalink).
2) Use only url-permalink

I would prefer 2). Only downside I see is if we click on a permalink from the map¹, full page reloads. It's even adressable with a click handler + history.pushState(). But I don't realy mind about that edge-case, and you ?

¹ but why the hell would you do that, except by accident ?

**Comment by opi** [comment]
I rather choose to use only one format of permalink, so we should go with url permalink :  `/map?id=ID` or the cleaner `/map/ID` ?

For the downside of page reload, I don't really care, this is a lightweight application.

**Comment by JocelynDelalande** [comment]
> /map?id=ID or the cleaner /map/ID ?

:+1: /map/ID

**Comment by bikepunk** [comment]
https://code.ffdn.org/FFDN/wifi-with-me/issues/18
