### ISSUE TITLE
Make people be able to contact each other directly

### ISSUE THREAD

**Issue by kheops2713** [JocelynDelalande/wifi-with-me#22]
Two people that seem to be able to interconnect after looking at the map may want to actually get in touch one with the other without passing through our human filter.

In link with issue #21, someone who has already registered could send some kind of notification to any other publicly-appearing user. We would not reveal their personal email address, we would just relay a sort of message/notification. And then they could choose to give the other person their email address to get in touch directly, and then have fun with antennas as they wish.

**Comment by JocelynDelalande** [comment]
Yeah, wifi-with-me as first wireless-based dating website ;-)

Seriously, why not, the same way leboncoin.fr does (a webform, the website relays to the recipients). It may even not be required to be registered on the website.

In the spirit, I'm pretty favorable in encouraging people to "peer" directly, the ISP may be an helper, but is not required.

**Comment by bikepunk** [comment]
https://code.ffdn.org/FFDN/wifi-with-me/issues/16
