### ISSUE TITLE
Do something with the private JSON data

### ISSUE THREAD

**Issue by zorun** [JocelynDelalande/wifi-with-me#25]
Is there any plan yet for using the private JSON data?

The obvious way would be to display the exact same map than the public one, but with all private information on it.

The question is how to to authenticate access to this private map.  It can either be done at the webserver level, or enforced directly in wifi-with-me.  Maybe a simple list of login/password would do?  Or it there a generic way to do authentication with bottlepy?

**Comment by JocelynDelalande** [comment]
First thing I see would be to display a count of how many private records are stored, just in order not to forget them.

Maybe a second map, requiring auth would do the job then. I think not implementing accounts system is a good thing. We all have many means to authenticate our users already... A proposal :
- define in WWM conf a key (think api-key)
- create two endpoints, both of them require the api-key to be set in conf and a named header (ex: `X-API-Key`) on protected request to match it.
  -  `/map-private/` a leaflet map with both private.json and public.json
  - `private.json`
- this key can then either be used directly by client, or, far better, configure the _httpd_ to add this header **and** to do auth/authz at HTTP level

**Comment by JocelynDelalande** [comment]
(simple) related idea in #26

**Comment by bikepunk** [comment]
here is a stub of a djago admin web interface for wifi-with-me
https://gitlab.com/vindarel/wifi-with-django
it's supposed to become a full django rewrite of wifi-with-me someday

**Comment by JocelynDelalande** [comment]
Cool :-)

**Comment by JocelynDelalande** [comment]
@bikepunk @vindarel when it will come to be a full rewrite, I'm ok if it's a replacement of the current wifi-with-me. I see no real reason to keep bottle and I'm ok to drop it (@opi @zorun  what do you think ?).

To put it short, @vindarel do as you fancy, but if you want to start working on a branch here, you're more than welcome :-).

(We could also take this opportunity to move to https://code.ffdn.org/ ?)

**Comment by bikepunk** [comment]
https://code.ffdn.org/FFDN/wifi-with-me/issues/13
