### ISSUE TITLE
Write ansible playbook

### ISSUE THREAD

**Issue by JocelynDelalande** [JocelynDelalande/wifi-with-me#6]
Write ansible playbook

**Comment by JocelynDelalande** [comment]
@TheCapsLock si c'est ok pour toi, je merge.

**Comment by TheCapsLock** [comment]
Seems ok to me ;
Personnally I would have used pip instead of packages from the distro ; runsv or supervirord instead of initscript ; installed the application in the home directory of wwm_user

**Comment by JocelynDelalande** [comment]
Ok, I merge it as-is, because it's functional as-is, but feel free to submit some patch if you end up to something generic enough.
