### ISSUE TITLE
Enable user to choose for how long their data will be stored

### ISSUE THREAD

**Issue by kheops2713** [JocelynDelalande/wifi-with-me#9]
It would be really respectful to the user if they can explictly set a duration at the end of which their personal data will be deleted from our database. After all, it's their data...

**Comment by JocelynDelalande** [comment]
@kheops2713 well, interesting idea but it's not the most trivial feature : todo includes classical ui/db + something to clear out the data at the given time.

I won't have time to code that soon, and considering the time this development lasted already, I would appreciate to see it deployed, with or without this patch, do you see it as "release-blocker" for FAIMaison or is it ok with something that may be added in the future ?

**Comment by kheops2713** [comment]
On the wifi-with-me site this really includes only the UI+DB part. Then the server (or even humans) can take care of removing data when it's considered expired.

If we don't give the user this choice then I think we should, as a minimum : 

- tell the user their data could be stored for an infinite period of time;
- decide among ourselves for how long we store the data.

I don't think we should start storing personal data before making a decision on the duration of this storage and be able to clearly state it.

**Comment by kheops2713** [comment]
How big is the work to just add a field in the page and the necessary fields in the DB? Basically just a submission date (maybe already present) and an expiration date.

**Comment by JocelynDelalande** [comment]
Another simple option, for FAIMaison at least is just to notify the user that we store the data for 1 year (that's on our CNIL declaration), unless they ask for removal, and to enforce that, by script or by human intervention. 

To avoid losing interesting data we could, in the future, ask some users if they want to keep (=renew) their data, before it expire, no answer on their side = we destroy the data.

@kheops2713 what do you think about it ?
